name: Test
on: [push]

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        uses: actions/checkout@v2
        run: |
          echo 'hellooo world'

      - name: Checkout dailyco-metrics
        uses: actions/checkout@v2
        with:
          repository: vipyne/dailyco-metrics
          token: ${{ secrets.KHK_MANUAL_TESTS_VIPYNE_PAT }}
          ref: main
          path: dailyco-metrics
